import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Filter from "../components/Filter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LHL final project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Filter />
        {children}
        </body>
    </html>
  );
}