const users = [
  {
    email: 'user1@example.com',
    username: 'john',
    password: 'password123',
    first_name: 'John',
    last_name: 'Doe'
  },
  {
    email: 'user2@example.com',
    username: 'jane',
    password: 'password456',
    first_name: 'Jane',
    last_name: 'Smith'
  },
  {
    email: 'user3@example.com',
    username: 'michael',
    password: 'password789',
    first_name: 'Michael',
    last_name: 'Johnson'
  },
  {
    email: 'user4@example.com',
    username: 'robert',
    password: 'password123',
    first_name: 'Robert',
    last_name: 'Brown'
  },
  {
    email: 'user5@example.com',
    username: 'sarah',
    password: 'password456',
    first_name: 'Sarah',
    last_name: 'Taylor'
  },
  {
    email: 'user6@example.com',
    username: 'david',
    password: 'password789',
    first_name: 'David',
    last_name: 'Anderson'
  },
  {
    email: 'user7@example.com',
    username: 'emily',
    password: 'password123',
    first_name: 'Emily',
    last_name: 'Wilson'
  },
  {
    email: 'user8@example.com',
    username: 'chris',
    password: 'password456',
    first_name: 'Christopher',
    last_name: 'Martinez'
  },
  {
    email: 'user9@example.com',
    username: 'amanda',
    password: 'password789',
    first_name: 'Amanda',
    last_name: 'Garcia'
  },
  {
    email: 'user10@example.com',
    username: 'william',
    password: 'password123',
    first_name: 'William',
    last_name: 'Jackson'
  }
];

const locationRatings = [
  { user_id: 1, location_id: 1, rating: 5, comment: "Absolutely stunning views! Must visit." },
  { user_id: 2, location_id: 1, rating: 3, comment: "Nice place, but a bit crowded." },
  { user_id: 3, location_id: 1, rating: 4, comment: "Great photo opportunities, worth the visit." },
  { user_id: 4, location_id: 15, rating: 4, comment: "Lovely scenery, relaxing atmosphere." },
  { user_id: 5, location_id: 15, rating: 2, comment: "Too touristy, couldn't enjoy much." },
  { user_id: 6, location_id: 15, rating: 5, comment: "Charming place, lots to explore." },
  { user_id: 7, location_id: 30, rating: 3, comment: "Interesting history, but needs better maintenance." },
  { user_id: 8, location_id: 30, rating: 4, comment: "Educational experience, enjoyed the exhibits." },
  { user_id: 9, location_id: 30, rating: 2, comment: "Underwhelming, expected more from the reviews." },
  { user_id: 10, location_id: 45, rating: 5, comment: "Absolutely breathtaking, exceeded expectations." },
  { user_id: 1, location_id: 45, rating: 4, comment: "Magical ambiance, perfect for a romantic evening." },
  { user_id: 2, location_id: 45, rating: 3, comment: "Nice views, but service could be improved." },
  { user_id: 3, location_id: 12, rating: 3, comment: "Average beach, nothing exceptional." },
  { user_id: 4, location_id: 12, rating: 5, comment: "Clean and serene, enjoyed every moment." },
  { user_id: 5, location_id: 12, rating: 1, comment: "Disappointing, wouldn't recommend." },
  { user_id: 6, location_id: 25, rating: 5, comment: "Fascinating insights into the past, highly recommend the tour." },
  { user_id: 7, location_id: 25, rating: 4, comment: "Well-preserved site, informative guides." },
  { user_id: 8, location_id: 25, rating: 2, comment: "Not much to see, expected more artifacts." },
  { user_id: 9, location_id: 40, rating: 4, comment: "Nice park, good for a leisurely stroll." },
  { user_id: 10, location_id: 40, rating: 3, comment: "Decent facilities, but could use more greenery." },
  { user_id: 1, location_id: 40, rating: 5, comment: "Beautifully landscaped, great for picnics." },
  { user_id: 2, location_id: 55, rating: 3, comment: "Scenic views, but crowded during weekends." },
  { user_id: 3, location_id: 55, rating: 5, comment: "Absolutely stunning, a hidden gem." },
  { user_id: 4, location_id: 55, rating: 4, comment: "Peaceful ambiance, perfect for relaxation." },
  { user_id: 5, location_id: 10, rating: 2, comment: "Crowded beach, difficult to find a spot." },
  { user_id: 6, location_id: 10, rating: 4, comment: "Clean and well-maintained, enjoyed the facilities." },
  { user_id: 7, location_id: 10, rating: 3, comment: "Nice beach, but too many vendors." },
  { user_id: 8, location_id: 20, rating: 5, comment: "Absolutely loved it, unique experience." },
  { user_id: 9, location_id: 20, rating: 2, comment: "Overrated, wouldn't visit again." },
  { user_id: 10, location_id: 20, rating: 4, comment: "Great historical significance, informative guides." },
  { user_id: 1, location_id: 35, rating: 3, comment: "Interesting exhibits, but too crowded." },
  { user_id: 2, location_id: 35, rating: 4, comment: "Fascinating artifacts, worth the visit." },
  { user_id: 3, location_id: 35, rating: 5, comment: "Educational experience, loved every moment." },
  { user_id: 4, location_id: 50, rating: 3, comment: "Tranquil gardens, perfect for a peaceful stroll." },
  { user_id: 5, location_id: 50, rating: 2, comment: "Not well-maintained, could be more scenic." },
  { user_id: 6, location_id: 50, rating: 4, comment: "Beautifully landscaped, enjoyed the serenity." },
  { user_id: 7, location_id: 5, rating: 5, comment: "Thrilling hike, breathtaking views." },
  { user_id: 8, location_id: 5, rating: 3, comment: "Scenic trail, but too crowded on weekends." },
  { user_id: 9, location_id: 5, rating: 4, comment: "Amazing vistas, worth the effort." },
  { user_id: 10, location_id: 18, rating: 3, comment: "Interesting architecture, but lacks amenities." },
  { user_id: 1, location_id: 18, rating: 4, comment: "Architectural marvel, enjoyed exploring." },
  { user_id: 2, location_id: 18, rating: 2, comment: "Not well-maintained, disappointing visit." },
  { user_id: 3, location_id: 33, rating: 2, comment: "Overpriced tickets, not worth the cost." },
  { user_id: 4, location_id: 33, rating: 4, comment: "Interesting exhibits, but too crowded." },
  { user_id: 5, location_id: 33, rating: 5, comment: "Well-curated displays, educational visit." },
  { user_id: 6, location_id: 33, rating: 1, comment: "Waste of money, wouldn't recommend." },
  { user_id: 7, location_id: 48, rating: 4, comment: "Delicious local cuisine, unique experience." },
  { user_id: 8, location_id: 48, rating: 5, comment: "Authentic flavors, loved every bite." },
  { user_id: 9, location_id: 48, rating: 3, comment: "Interesting food options, but service could be better." },
  { user_id: 10, location_id: 8, rating: 5, comment: "Absolutely loved it, perfect for a family day out." },
  { user_id: 1, location_id: 8, rating: 4, comment: "Great recreational activities, enjoyable for all ages." },
  { user_id: 2, location_id: 8, rating: 2, comment: "Lack of facilities, needs improvement." },
  { user_id: 3, location_id: 22, rating: 3, comment: "Nice park, but could use more amenities." },
  { user_id: 4, location_id: 22, rating: 4, comment: "Beautiful scenery, great for a morning walk." },
  { user_id: 5, location_id: 22, rating: 5, comment: "Peaceful ambiance, loved the greenery." },
  { user_id: 6, location_id: 38, rating: 4, comment: "Good facilities, clean environment." },
  { user_id: 7, location_id: 38, rating: 5, comment: "Family-friendly atmosphere, enjoyable for all." },
  { user_id: 8, location_id: 38, rating: 3, comment: "Decent amenities, but could use more variety." },
  { user_id: 9, location_id: 52, rating: 1, comment: "Waste of time and money, avoid at all costs." },
  { user_id: 10, location_id: 52, rating: 2, comment: "Disappointing experience, wouldn't recommend." },
  { user_id: 1, location_id: 52, rating: 3, comment: "Average at best, expected more from the reviews." },
  { user_id: 2, location_id: 4, rating: 5, comment: "Spectacular views, worth the trek." },
  { user_id: 3, location_id: 4, rating: 4, comment: "Breathtaking scenery, loved every moment." },
  { user_id: 4, location_id: 4, rating: 3, comment: "Nice hike, but too crowded on weekends." },
  { user_id: 5, location_id: 64, rating: 2, comment: "Underwhelming, not much to see." },
  { user_id: 6, location_id: 64, rating: 4, comment: "Interesting exhibits, enjoyed the visit." },
  { user_id: 7, location_id: 64, rating: 3, comment: "Informative displays, but lacking in interactive features." },
  { user_id: 8, location_id: 69, rating: 5, comment: "Absolutely stunning, a must-visit destination." },
  { user_id: 9, location_id: 69, rating: 4, comment: "Beautiful natural surroundings, great for hiking." },
  { user_id: 10, location_id: 69, rating: 3, comment: "Scenic views, but limited facilities." },
  { user_id: 1, location_id: 2, rating: 4, comment: "Charming little town, friendly locals." },
  { user_id: 2, location_id: 2, rating: 3, comment: "Quaint atmosphere, worth a short visit." },
  { user_id: 3, location_id: 2, rating: 5, comment: "Picturesque views, loved exploring the streets." },
  { user_id: 4, location_id: 3, rating: 5, comment: "Incredible architecture, a photographer's paradise." },
  { user_id: 5, location_id: 3, rating: 4, comment: "Historically rich, enjoyed the guided tour." },
  { user_id: 6, location_id: 3, rating: 3, comment: "Interesting sights, but too crowded." },
  { user_id: 7, location_id: 6, rating: 3, comment: "Decent park, good for a leisurely walk." },
  { user_id: 8, location_id: 6, rating: 4, comment: "Nice greenery, peaceful ambiance." },
  { user_id: 9, location_id: 6, rating: 5, comment: "Relaxing atmosphere, great for picnics." },
  { user_id: 10, location_id: 7, rating: 2, comment: "Disappointing, not much to see." },
  { user_id: 1, location_id: 7, rating: 3, comment: "Average experience, expected more attractions." },
  { user_id: 2, location_id: 7, rating: 4, comment: "Nice views, enjoyed the scenic overlook." },
  { user_id: 3, location_id: 9, rating: 5, comment: "Absolutely breathtaking, panoramic views." },
  { user_id: 4, location_id: 9, rating: 4, comment: "Great hiking trails, stunning vistas." },
  { user_id: 5, location_id: 9, rating: 3, comment: "Nice views, but too crowded on weekends." },
  { user_id: 6, location_id: 11, rating: 4, comment: "Charming village, loved the local shops." },
  { user_id: 7, location_id: 11, rating: 5, comment: "Quaint atmosphere, friendly locals." },
  { user_id: 8, location_id: 11, rating: 3, comment: "Nice for a short visit, limited attractions." },
  { user_id: 9, location_id: 13, rating: 5, comment: "Serene beach, crystal-clear waters." },
  { user_id: 10, location_id: 13, rating: 4, comment: "Great for swimming, enjoyed the waves." },
  { user_id: 1, location_id: 13, rating: 3, comment: "Crowded beach, difficult to find a spot." },
  { user_id: 2, location_id: 14, rating: 2, comment: "Overrated, not worth the hype." },
  { user_id: 3, location_id: 14, rating: 3, comment: "Average experience, expected more." },
  { user_id: 4, location_id: 14, rating: 4, comment: "Nice views, but too many tourists." },
  { user_id: 5, location_id: 16, rating: 5, comment: "Exquisite architecture, worth the visit." },
  { user_id: 6, location_id: 16, rating: 4, comment: "Beautiful interiors, enjoyed the guided tour." },
  { user_id: 7, location_id: 16, rating: 3, comment: "Interesting history, but lacks signage." },
  { user_id: 8, location_id: 17, rating: 4, comment: "Peaceful gardens, great for relaxation." },
  { user_id: 9, location_id: 17, rating: 5, comment: "Beautifully landscaped, enjoyed the stroll." },
  { user_id: 10, location_id: 17, rating: 3, comment: "Nice views, but not much else to see." },
  { user_id: 1, location_id: 19, rating: 3, comment: "Interesting exhibits, but lacks variety." },
  { user_id: 2, location_id: 19, rating: 4, comment: "Educational experience, enjoyed the tour." },
  { user_id: 3, location_id: 19, rating: 5, comment: "Fascinating artifacts, worth a visit." },
  { user_id: 4, location_id: 21, rating: 4, comment: "Scenic lookout, breathtaking views." },
  { user_id: 5, location_id: 21, rating: 3, comment: "Nice for a short visit, limited amenities." },
  { user_id: 6, location_id: 21, rating: 5, comment: "Absolutely stunning, a must-visit destination." },
  { user_id: 7, location_id: 23, rating: 2, comment: "Disappointing, not much to see." },
  { user_id: 8, location_id: 23, rating: 3, comment: "Average experience, expected more attractions." },
  { user_id: 9, location_id: 23, rating: 4, comment: "Nice views, enjoyed the scenic overlook." },
  { user_id: 10, location_id: 24, rating: 5, comment: "Absolutely breathtaking, panoramic views." },
  { user_id: 1, location_id: 24, rating: 4, comment: "Great hiking trails, stunning vistas." },
  { user_id: 2, location_id: 24, rating: 3, comment: "Nice views, but too crowded on weekends." },
  { user_id: 3, location_id: 26, rating: 4, comment: "Charming village, loved the local shops." },
  { user_id: 4, location_id: 26, rating: 5, comment: "Quaint atmosphere, friendly locals." },
  { user_id: 5, location_id: 26, rating: 3, comment: "Nice for a short visit, limited attractions." },
  { user_id: 6, location_id: 27, rating: 5, comment: "Serene beach, crystal-clear waters." },
  { user_id: 7, location_id: 27, rating: 4, comment: "Great for swimming, enjoyed the waves." },
  { user_id: 8, location_id: 27, rating: 3, comment: "Crowded beach, difficult to find a spot." },
  { user_id: 9, location_id: 28, rating: 2, comment: "Overrated, not worth the hype." },
  { user_id: 10, location_id: 28, rating: 3, comment: "Average experience, expected more." },
  { user_id: 1, location_id: 28, rating: 4, comment: "Nice views, but too many tourists." },
  { user_id: 2, location_id: 29, rating: 5, comment: "Exquisite architecture, worth the visit." },
  { user_id: 3, location_id: 29, rating: 4, comment: "Beautiful interiors, enjoyed the guided tour." },
  { user_id: 4, location_id: 29, rating: 3, comment: "Interesting history, but lacks signage." },
  { user_id: 5, location_id: 31, rating: 4, comment: "Peaceful gardens, great for relaxation." },
  { user_id: 6, location_id: 31, rating: 5, comment: "Beautifully landscaped, enjoyed the stroll." },
  { user_id: 7, location_id: 31, rating: 3, comment: "Nice views, but not much else to see." },
  { user_id: 8, location_id: 32, rating: 3, comment: "Interesting exhibits, but lacks variety." },
  { user_id: 9, location_id: 32, rating: 4, comment: "Educational experience, enjoyed the tour." },
  { user_id: 10, location_id: 32, rating: 5, comment: "Fascinating artifacts, worth a visit." },
  { user_id: 1, location_id: 34, rating: 4, comment: "Scenic lookout, breathtaking views." },
  { user_id: 2, location_id: 34, rating: 3, comment: "Nice for a short visit, limited amenities." },
  { user_id: 3, location_id: 34, rating: 5, comment: "Absolutely stunning, a must-visit destination." },
  { user_id: 4, location_id: 36, rating: 2, comment: "Disappointing, not much to see." },
  { user_id: 5, location_id: 36, rating: 3, comment: "Average experience, expected more attractions." },
  { user_id: 6, location_id: 36, rating: 4, comment: "Nice views, enjoyed the scenic overlook." },
  { user_id: 7, location_id: 37, rating: 5, comment: "Absolutely breathtaking, panoramic views." },
  { user_id: 8, location_id: 37, rating: 4, comment: "Great hiking trails, stunning vistas." },
  { user_id: 9, location_id: 37, rating: 3, comment: "Nice views, but too crowded on weekends." },
  { user_id: 10, location_id: 39, rating: 4, comment: "Charming village, loved the local shops." },
  { user_id: 1, location_id: 39, rating: 5, comment: "Quaint atmosphere, friendly locals." },
  { user_id: 2, location_id: 39, rating: 3, comment: "Nice for a short visit, limited attractions." },
  { user_id: 3, location_id: 41, rating: 5, comment: "Serene beach, crystal-clear waters." },
  { user_id: 4, location_id: 41, rating: 4, comment: "Great for swimming, enjoyed the waves." },
  { user_id: 5, location_id: 41, rating: 3, comment: "Crowded beach, difficult to find a spot." },
  { user_id: 6, location_id: 42, rating: 2, comment: "Overrated, not worth the hype." },
  { user_id: 7, location_id: 42, rating: 3, comment: "Average experience, expected more." },
  { user_id: 8, location_id: 42, rating: 4, comment: "Nice views, but too many tourists." },
  { user_id: 9, location_id: 43, rating: 5, comment: "Exquisite architecture, worth the visit." },
  { user_id: 10, location_id: 43, rating: 4, comment: "Beautiful interiors, enjoyed the guided tour." },
  { user_id: 1, location_id: 43, rating: 3, comment: "Interesting history, but lacks signage." },
  { user_id: 2, location_id: 44, rating: 4, comment: "Peaceful gardens, great for relaxation." },
  { user_id: 3, location_id: 44, rating: 5, comment: "Beautifully landscaped, enjoyed the stroll." },
  { user_id: 4, location_id: 44, rating: 3, comment: "Nice views, but not much else to see." },
  { user_id: 5, location_id: 46, rating: 3, comment: "Interesting exhibits, but lacks variety." },
  { user_id: 6, location_id: 46, rating: 4, comment: "Educational experience, enjoyed the tour." },
  { user_id: 7, location_id: 46, rating: 5, comment: "Fascinating artifacts, worth a visit." },
  { user_id: 8, location_id: 47, rating: 4, comment: "Scenic lookout, breathtaking views." },
  { user_id: 9, location_id: 47, rating: 3, comment: "Nice for a short visit, limited amenities." },
  { user_id: 10, location_id: 47, rating: 5, comment: "Absolutely stunning, a must-visit destination." },
  { user_id: 1, location_id: 49, rating: 2, comment: "Disappointing, not much to see." },
  { user_id: 2, location_id: 49, rating: 3, comment: "Average experience, expected more attractions." },
  { user_id: 3, location_id: 49, rating: 4, comment: "Nice views, enjoyed the scenic overlook." },
  { user_id: 4, location_id: 51, rating: 5, comment: "Absolutely breathtaking, panoramic views." },
  { user_id: 5, location_id: 51, rating: 4, comment: "Great hiking trails, stunning vistas." },
  { user_id: 6, location_id: 51, rating: 3, comment: "Nice views, but too crowded on weekends." },
  { user_id: 7, location_id: 53, rating: 4, comment: "Charming village, loved the local shops." },
  { user_id: 8, location_id: 53, rating: 5, comment: "Quaint atmosphere, friendly locals." },
  { user_id: 9, location_id: 53, rating: 3, comment: "Nice for a short visit, limited attractions." },
  { user_id: 10, location_id: 54, rating: 5, comment: "Serene beach, crystal-clear waters." },
  { user_id: 1, location_id: 54, rating: 4, comment: "Great for swimming, enjoyed the waves." },
  { user_id: 2, location_id: 54, rating: 3, comment: "Crowded beach, difficult to find a spot." },
  { user_id: 3, location_id: 56, rating: 2, comment: "Overrated, not worth the hype." },
  { user_id: 4, location_id: 56, rating: 3, comment: "Average experience, expected more." },
  { user_id: 5, location_id: 56, rating: 4, comment: "Nice views, but too many tourists." },
  { user_id: 6, location_id: 57, rating: 5, comment: "Exquisite architecture, worth the visit." },
  { user_id: 7, location_id: 57, rating: 4, comment: "Beautiful interiors, enjoyed the guided tour." },
  { user_id: 8, location_id: 57, rating: 3, comment: "Interesting history, but lacks signage." },
  { user_id: 9, location_id: 58, rating: 4, comment: "Peaceful gardens, great for relaxation." },
  { user_id: 10, location_id: 58, rating: 5, comment: "Beautifully landscaped, enjoyed the stroll." },
  { user_id: 1, location_id: 58, rating: 3, comment: "Nice views, but not much else to see." },
  { user_id: 2, location_id: 59, rating: 3, comment: "Interesting exhibits, but lacks variety." },
  { user_id: 3, location_id: 59, rating: 4, comment: "Educational experience, enjoyed the tour." },
  { user_id: 4, location_id: 59, rating: 5, comment: "Fascinating artifacts, worth a visit." },
  { user_id: 5, location_id: 61, rating: 4, comment: "Scenic lookout, breathtaking views." },
  { user_id: 6, location_id: 61, rating: 3, comment: "Nice for a short visit, limited amenities." },
  { user_id: 7, location_id: 61, rating: 5, comment: "Absolutely stunning, a must-visit destination." },
  { user_id: 8, location_id: 62, rating: 2, comment: "Disappointing, not much to see." },
  { user_id: 9, location_id: 62, rating: 3, comment: "Average experience, expected more attractions." },
  { user_id: 10, location_id: 62, rating: 4, comment: "Nice views, enjoyed the scenic overlook." },
  { user_id: 1, location_id: 63, rating: 5, comment: "Absolutely breathtaking, panoramic views." },
  { user_id: 2, location_id: 63, rating: 4, comment: "Great hiking trails, stunning vistas." },
  { user_id: 3, location_id: 63, rating: 3, comment: "Nice views, but too crowded on weekends." },
  { user_id: 4, location_id: 65, rating: 4, comment: "Charming village, loved the local shops." },
  { user_id: 5, location_id: 65, rating: 5, comment: "Quaint atmosphere, friendly locals." },
  { user_id: 6, location_id: 65, rating: 3, comment: "Nice for a short visit, limited attractions." },
  { user_id: 7, location_id: 66, rating: 5, comment: "Serene beach, crystal-clear waters." },
  { user_id: 8, location_id: 66, rating: 4, comment: "Great for swimming, enjoyed the waves." },
  { user_id: 9, location_id: 66, rating: 3, comment: "Crowded beach, difficult to find a spot." },
  { user_id: 10, location_id: 67, rating: 2, comment: "Overrated, not worth the hype." },
  { user_id: 1, location_id: 67, rating: 3, comment: "Average experience, expected more." },
  { user_id: 2, location_id: 67, rating: 4, comment: "Nice views, but too many tourists." },
  { user_id: 3, location_id: 68, rating: 5, comment: "Exquisite architecture, worth the visit." },
  { user_id: 4, location_id: 68, rating: 4, comment: "Beautiful interiors, enjoyed the guided tour." },
  { user_id: 5, location_id: 68, rating: 3, comment: "Interesting history, but lacks signage." },
  { user_id: 6, location_id: 69, rating: 4, comment: "Peaceful gardens, great for relaxation." },
  { user_id: 7, location_id: 69, rating: 5, comment: "Beautifully landscaped, enjoyed the stroll." },
  { user_id: 8, location_id: 69, rating: 3, comment: "Nice views, but not much else to see." },
  { user_id: 1, location_id: 2, rating: 4, comment: "Charming little town, friendly locals." },
  { user_id: 2, location_id: 2, rating: 3, comment: "Quaint atmosphere, worth a short visit." },
  { user_id: 3, location_id: 2, rating: 5, comment: "Picturesque views, loved exploring the streets." },
  { user_id: 4, location_id: 3, rating: 5, comment: "Incredible architecture, a photographer's paradise." },
  { user_id: 5, location_id: 3, rating: 4, comment: "Historically rich, enjoyed the guided tour." },
  { user_id: 6, location_id: 3, rating: 3, comment: "Interesting sights, but too crowded." },
  { user_id: 7, location_id: 6, rating: 3, comment: "Decent park, good for a leisurely walk." },
  { user_id: 8, location_id: 6, rating: 4, comment: "Nice greenery, peaceful ambiance." },
  { user_id: 9, location_id: 6, rating: 5, comment: "Relaxing atmosphere, great for picnics." },
  { user_id: 10, location_id: 7, rating: 2, comment: "Disappointing, not much to see." },
  { user_id: 1, location_id: 7, rating: 3, comment: "Average experience, expected more attractions." },
  { user_id: 2, location_id: 7, rating: 4, comment: "Nice views, enjoyed the scenic overlook." },
  { user_id: 3, location_id: 9, rating: 5, comment: "Absolutely breathtaking, panoramic views." },
  { user_id: 4, location_id: 9, rating: 4, comment: "Great hiking trails, stunning vistas." },
  { user_id: 5, location_id: 9, rating: 3, comment: "Nice views, but too crowded on weekends." },
  { user_id: 6, location_id: 11, rating: 4, comment: "Charming village, loved the local shops." },
  { user_id: 7, location_id: 11, rating: 5, comment: "Quaint atmosphere, friendly locals." },
  { user_id: 8, location_id: 11, rating: 3, comment: "Nice for a short visit, limited attractions." },
  { user_id: 9, location_id: 13, rating: 5, comment: "Serene beach, crystal-clear waters." },
  { user_id: 10, location_id: 13, rating: 4, comment: "Great for swimming, enjoyed the waves." },
  { user_id: 1, location_id: 13, rating: 3, comment: "Crowded beach, difficult to find a spot." },
  { user_id: 2, location_id: 14, rating: 2, comment: "Overrated, not worth the hype." },
  { user_id: 3, location_id: 14, rating: 3, comment: "Average experience, expected more." },
  { user_id: 4, location_id: 14, rating: 4, comment: "Nice views, but too many tourists." },
  { user_id: 5, location_id: 16, rating: 5, comment: "Exquisite architecture, worth the visit." },
  { user_id: 6, location_id: 16, rating: 4, comment: "Beautiful interiors, enjoyed the guided tour." },
  { user_id: 7, location_id: 16, rating: 3, comment: "Interesting history, but lacks signage." },
  { user_id: 8, location_id: 17, rating: 4, comment: "Peaceful gardens, great for relaxation." },
  { user_id: 9, location_id: 17, rating: 5, comment: "Beautifully landscaped, enjoyed the stroll." },
  { user_id: 10, location_id: 17, rating: 3, comment: "Nice views, but not much else to see." },
  { user_id: 1, location_id: 19, rating: 3, comment: "Interesting exhibits, but lacks variety." },
  { user_id: 2, location_id: 19, rating: 4, comment: "Educational experience, enjoyed the tour." },
  { user_id: 3, location_id: 19, rating: 5, comment: "Fascinating artifacts, worth a visit." },
  { user_id: 4, location_id: 21, rating: 4, comment: "Scenic lookout, breathtaking views." },
  { user_id: 5, location_id: 21, rating: 3, comment: "Nice for a short visit, limited amenities." },
  { user_id: 6, location_id: 21, rating: 5, comment: "Absolutely stunning, a must-visit destination." },
  { user_id: 7, location_id: 23, rating: 2, comment: "Disappointing, not much to see." },
  { user_id: 8, location_id: 23, rating: 3, comment: "Average experience, expected more attractions." },
  { user_id: 9, location_id: 23, rating: 4, comment: "Nice views, enjoyed the scenic overlook." },
  { user_id: 10, location_id: 24, rating: 5, comment: "Absolutely breathtaking, panoramic views." },
  { user_id: 1, location_id: 24, rating: 4, comment: "Great hiking trails, stunning vistas." },
  { user_id: 2, location_id: 24, rating: 3, comment: "Nice views, but too crowded on weekends." },
  { user_id: 3, location_id: 26, rating: 4, comment: "Charming village, loved the local shops." },
  { user_id: 4, location_id: 26, rating: 5, comment: "Quaint atmosphere, friendly locals." },
  { user_id: 5, location_id: 26, rating: 3, comment: "Nice for a short visit, limited attractions." },
  { user_id: 6, location_id: 27, rating: 5, comment: "Serene beach, crystal-clear waters." },
  { user_id: 7, location_id: 27, rating: 4, comment: "Great for swimming, enjoyed the waves." },
  { user_id: 8, location_id: 27, rating: 3, comment: "Crowded beach, difficult to find a spot." },
  { user_id: 9, location_id: 28, rating: 2, comment: "Overrated, not worth the hype." },
  { user_id: 10, location_id: 28, rating: 3, comment: "Average experience, expected more." },
  { user_id: 1, location_id: 28, rating: 4, comment: "Nice views, but too many tourists." },
  { user_id: 2, location_id: 29, rating: 5, comment: "Exquisite architecture, worth the visit." },
  { user_id: 3, location_id: 29, rating: 4, comment: "Beautiful interiors, enjoyed the guided tour." },
  { user_id: 4, location_id: 29, rating: 3, comment: "Interesting history, but lacks signage." },
  { user_id: 5, location_id: 31, rating: 4, comment: "Peaceful gardens, great for relaxation." },
  { user_id: 6, location_id: 31, rating: 5, comment: "Beautifully landscaped, enjoyed the stroll." },
  { user_id: 7, location_id: 31, rating: 3, comment: "Nice views, but not much else to see." },
  { user_id: 8, location_id: 32, rating: 3, comment: "Interesting exhibits, but lacks variety." },
  { user_id: 9, location_id: 32, rating: 4, comment: "Educational experience, enjoyed the tour." },
  { user_id: 10, location_id: 32, rating: 5, comment: "Fascinating artifacts, worth a visit." },
  { user_id: 1, location_id: 34, rating: 4, comment: "Scenic lookout, breathtaking views." },
  { user_id: 2, location_id: 34, rating: 3, comment: "Nice for a short visit, limited amenities." },
  { user_id: 3, location_id: 34, rating: 5, comment: "Absolutely stunning, a must-visit destination." },
  { user_id: 4, location_id: 36, rating: 2, comment: "Disappointing, not much to see." },
  { user_id: 5, location_id: 36, rating: 3, comment: "Average experience, expected more attractions." },
  { user_id: 6, location_id: 36, rating: 4, comment: "Nice views, enjoyed the scenic overlook." },
  { user_id: 7, location_id: 37, rating: 5, comment: "Absolutely breathtaking, panoramic views." },
  { user_id: 8, location_id: 37, rating: 4, comment: "Great hiking trails, stunning vistas." },
  { user_id: 9, location_id: 37, rating: 3, comment: "Nice views, but too crowded on weekends." },
  { user_id: 10, location_id: 39, rating: 4, comment: "Charming village, loved the local shops." },
  { user_id: 1, location_id: 39, rating: 5, comment: "Quaint atmosphere, friendly locals." },
  { user_id: 2, location_id: 39, rating: 3, comment: "Nice for a short visit, limited attractions." },
  { user_id: 3, location_id: 41, rating: 5, comment: "Serene beach, crystal-clear waters." },
  { user_id: 4, location_id: 41, rating: 4, comment: "Great for swimming, enjoyed the waves." },
  { user_id: 5, location_id: 41, rating: 3, comment: "Crowded beach, difficult to find a spot." },
  { user_id: 6, location_id: 42, rating: 2, comment: "Overrated, not worth the hype." },
  { user_id: 7, location_id: 42, rating: 3, comment: "Average experience, expected more." },
  { user_id: 8, location_id: 42, rating: 4, comment: "Nice views, but too many tourists." },
  { user_id: 9, location_id: 43, rating: 5, comment: "Exquisite architecture, worth the visit." },
  { user_id: 10, location_id: 43, rating: 4, comment: "Beautiful interiors, enjoyed the guided tour." },
  { user_id: 1, location_id: 43, rating: 3, comment: "Interesting history, but lacks signage." },
  { user_id: 2, location_id: 44, rating: 4, comment: "Peaceful gardens, great for relaxation." },
  { user_id: 3, location_id: 44, rating: 5, comment: "Beautifully landscaped, enjoyed the stroll." },
  { user_id: 4, location_id: 44, rating: 3, comment: "Nice views, but not much else to see." },
  { user_id: 5, location_id: 46, rating: 3, comment: "Interesting exhibits, but lacks variety." },
  { user_id: 6, location_id: 46, rating: 4, comment: "Educational experience, enjoyed the tour." },
  { user_id: 7, location_id: 46, rating: 5, comment: "Fascinating artifacts, worth a visit." },
  { user_id: 8, location_id: 47, rating: 4, comment: "Scenic lookout, breathtaking views." },
  { user_id: 9, location_id: 47, rating: 3, comment: "Nice for a short visit, limited amenities." },
  { user_id: 10, location_id: 47, rating: 5, comment: "Absolutely stunning, a must-visit destination." },
  { user_id: 1, location_id: 49, rating: 2, comment: "Disappointing, not much to see." },
  { user_id: 2, location_id: 49, rating: 3, comment: "Average experience, expected more attractions." },
  { user_id: 3, location_id: 49, rating: 4, comment: "Nice views, enjoyed the scenic overlook." },
  { user_id: 4, location_id: 51, rating: 5, comment: "Absolutely breathtaking, panoramic views." },
  { user_id: 5, location_id: 51, rating: 4, comment: "Great hiking trails, stunning vistas." },
  { user_id: 6, location_id: 51, rating: 3, comment: "Nice views, but too crowded on weekends." },
  { user_id: 7, location_id: 53, rating: 4, comment: "Charming village, loved the local shops." },
  { user_id: 8, location_id: 53, rating: 5, comment: "Quaint atmosphere, friendly locals." },
  { user_id: 9, location_id: 53, rating: 3, comment: "Nice for a short visit, limited attractions." },
  { user_id: 10, location_id: 54, rating: 5, comment: "Serene beach, crystal-clear waters." },
  { user_id: 1, location_id: 54, rating: 4, comment: "Great for swimming, enjoyed the waves." },
  { user_id: 2, location_id: 54, rating: 3, comment: "Crowded beach, difficult to find a spot." },
  { user_id: 3, location_id: 56, rating: 2, comment: "Overrated, not worth the hype." },
  { user_id: 4, location_id: 56, rating: 3, comment: "Average experience, expected more." },
  { user_id: 5, location_id: 56, rating: 4, comment: "Nice views, but too many tourists." },
  { user_id: 6, location_id: 57, rating: 5, comment: "Exquisite architecture, worth the visit." },
  { user_id: 7, location_id: 57, rating: 4, comment: "Beautiful interiors, enjoyed the guided tour." },
  { user_id: 8, location_id: 57, rating: 3, comment: "Interesting history, but lacks signage." },
  { user_id: 9, location_id: 58, rating: 4, comment: "Peaceful gardens, great for relaxation." },
  { user_id: 10, location_id: 58, rating: 5, comment: "Beautifully landscaped, enjoyed the stroll." },
  { user_id: 1, location_id: 58, rating: 3, comment: "Nice views, but not much else to see." },
  { user_id: 2, location_id: 59, rating: 3, comment: "Interesting exhibits, but lacks variety." },
  { user_id: 3, location_id: 59, rating: 4, comment: "Educational experience, enjoyed the tour." },
  { user_id: 4, location_id: 59, rating: 5, comment: "Fascinating artifacts, worth a visit." },
  { user_id: 5, location_id: 61, rating: 4, comment: "Scenic lookout, breathtaking views." },
  { user_id: 6, location_id: 61, rating: 3, comment: "Nice for a short visit, limited amenities." },
  { user_id: 7, location_id: 61, rating: 5, comment: "Absolutely stunning, a must-visit destination." },
  { user_id: 8, location_id: 62, rating: 2, comment: "Disappointing, not much to see." },
  { user_id: 9, location_id: 62, rating: 3, comment: "Average experience, expected more attractions." },
  { user_id: 10, location_id: 62, rating: 4, comment: "Nice views, enjoyed the scenic overlook." },
  { user_id: 1, location_id: 63, rating: 5, comment: "Absolutely breathtaking, panoramic views." },
  { user_id: 2, location_id: 63, rating: 4, comment: "Great hiking trails, stunning vistas." },
  { user_id: 3, location_id: 63, rating: 3, comment: "Nice views, but too crowded on weekends." },
  { user_id: 4, location_id: 65, rating: 4, comment: "Charming village, loved the local shops." },
  { user_id: 5, location_id: 65, rating: 5, comment: "Quaint atmosphere, friendly locals." },
  { user_id: 6, location_id: 65, rating: 3, comment: "Nice for a short visit, limited attractions." },
  { user_id: 7, location_id: 66, rating: 5, comment: "Serene beach, crystal-clear waters." },
  { user_id: 8, location_id: 66, rating: 4, comment: "Great for swimming, enjoyed the waves." },
  { user_id: 9, location_id: 66, rating: 3, comment: "Crowded beach, difficult to find a spot." },
  { user_id: 10, location_id: 67, rating: 2, comment: "Overrated, not worth the hype." },
  { user_id: 1, location_id: 67, rating: 3, comment: "Average experience, expected more." },
  { user_id: 2, location_id: 67, rating: 4, comment: "Nice views, but too many tourists." },
  { user_id: 3, location_id: 68, rating: 5, comment: "Exquisite architecture, worth the visit." },
  { user_id: 4, location_id: 68, rating: 4, comment: "Beautiful interiors, enjoyed the guided tour." },
  { user_id: 5, location_id: 68, rating: 3, comment: "Interesting history, but lacks signage." },
  { user_id: 6, location_id: 69, rating: 4, comment: "Peaceful gardens, great for relaxation." },
  { user_id: 7, location_id: 69, rating: 5, comment: "Beautifully landscaped, enjoyed the stroll." },
  { user_id: 8, location_id: 69, rating: 3, comment: "Nice views, but not much else to see." }
];

const routeRatings = [
  { user_id: 1, route_id: 1, rating: 4, comment: "The tour plan was well-organized and covered all the major attractions. However, the guide could have been more knowledgeable about the history of the sites. Overall, a good experience." },
  { user_id: 2, route_id: 2, rating: 5, comment: "Absolutely loved the route! Each stop was carefully selected, and the guide provided insightful commentary throughout the journey. Highly recommended!" },
  { user_id: 3, route_id: 3, rating: 3, comment: "The route had potential, but it felt rushed. We didn't have enough time to explore each destination properly. Also, some of the stops were underwhelming. Average experience." },
  { user_id: 4, route_id: 4, rating: 4, comment: "Great itinerary with a good balance of sightseeing and leisure time. The transportation was comfortable, and the guide was friendly and accommodating. Enjoyed every moment!" },
  { user_id: 5, route_id: 5, rating: 2, comment: "Disappointed with the route. It seemed hastily put together, and some of the attractions were closed for maintenance. Not worth the money." },
  { user_id: 6, route_id: 6, rating: 4, comment: "The route offered a diverse range of experiences, from cultural landmarks to scenic viewpoints. The guide was knowledgeable, and the accommodations were comfortable. Would do it again!" },
  { user_id: 7, route_id: 7, rating: 5, comment: "Exceeded expectations! The route took us off the beaten path to discover hidden gems. The guide was passionate about the destinations, making the experience truly memorable." },
  { user_id: 8, route_id: 8, rating: 3, comment: "Mixed feelings about the route. While some parts were enjoyable, others felt rushed or uninteresting. The guide tried their best, but the overall experience fell short of expectations." },
  { user_id: 9, route_id: 9, rating: 4, comment: "Thoroughly enjoyed the route! It was well-paced, allowing ample time to explore each location. The guide was informative, and the optional activities added extra excitement to the trip." },
  { user_id: 10, route_id: 10, rating: 1, comment: "Terrible route! The itinerary was poorly planned, and we spent more time on the bus than actually visiting attractions. Avoid at all costs!" },
  { user_id: 1, route_id: 10, rating: 4, comment: "A well-structured route with plenty of flexibility. The guide was accommodating to our preferences, and the optional excursions were a highlight. Would recommend to fellow travelers." },
  { user_id: 2, route_id: 9, rating: 5, comment: "An unforgettable journey! The route showcased the best of the region, from historical landmarks to natural wonders. The guide's passion for the destinations was infectious, making every moment enjoyable." },
  { user_id: 3, route_id: 8, rating: 3, comment: "Decent route, but could use some improvements. Some of the attractions were overcrowded, and the schedule felt rushed at times. Overall, an average experience." },
  { user_id: 4, route_id: 7, rating: 4, comment: "Thoroughly enjoyed the route! It was well-organized, and the guide provided insightful commentary throughout the journey. The accommodations were comfortable, and the included meals were delicious." },
  { user_id: 5, route_id: 6, rating: 2, comment: "Disappointing route. Many of the advertised attractions were closed for renovation, and the alternatives provided were not of the same caliber. Wouldn't recommend." },
  { user_id: 6, route_id: 5, rating: 4, comment: "A fantastic route with a great mix of cultural and outdoor experiences. The guide was knowledgeable and engaging, and the group dynamics made the trip even more enjoyable. Highly recommended!" },
  { user_id: 7, route_id: 4, rating: 5, comment: "Absolutely loved every moment of the route! The itinerary was well-designed, and the guide's passion for the destinations was evident. Each stop offered something unique, making the journey unforgettable." },
  { user_id: 8, route_id: 3, rating: 3, comment: "An average route with some highlights and lowlights. The itinerary felt a bit rushed, and some of the attractions were underwhelming. However, the guide was friendly and knowledgeable." },
  { user_id: 9, route_id: 2, rating: 4, comment: "Overall, a great route with plenty of memorable experiences. The guide was attentive to our needs, and the accommodations exceeded expectations. Would definitely consider another trip with this company." },
  { user_id: 10, route_id: 1, rating: 1, comment: "The worst route I've ever been on! The itinerary was poorly planned, and the guide lacked enthusiasm. Save your money and choose a different tour operator." },
  { user_id: 1, route_id: 1, rating: 4, comment: "The walking tour through the city's famous attractions was an enriching experience. The route was well-organized, taking us to all the major landmarks. However, the guide's knowledge about the history of the sites was lacking, which was a bit disappointing. Nonetheless, the tour provided valuable insights into the city's culture and heritage. The pace of the tour was comfortable, allowing us to explore each attraction thoroughly. The commentary provided by the guide was informative, although more depth on historical context would have been appreciated. Overall, it was a good experience and a great way to discover the city's highlights." },
  { user_id: 2, route_id: 1, rating: 5, comment: "Exploring the city's famous attractions through the walking tour route was an absolute delight. The route was meticulously planned, ensuring that we didn't miss any key landmarks. The guide was knowledgeable and passionate about the city's history, providing fascinating insights at each stop. The pacing of the tour was perfect, allowing ample time to admire each attraction. The commentary was engaging and informative, enhancing our understanding of the city's culture and heritage. The route offered a comprehensive overview of the city's highlights, making it an ideal introduction for first-time visitors. Overall, it was an excellent experience that exceeded our expectations." },
  { user_id: 3, route_id: 1, rating: 3, comment: "The walking tour route provided a decent overview of the city's famous attractions. While the route was well-planned and covered the major landmarks, the guide's commentary lacked depth. More historical context and interesting anecdotes would have made the tour more engaging. Additionally, the pacing of the tour felt rushed at times, leaving little opportunity to fully appreciate each site. However, the route itself was scenic, offering picturesque views of the city's architecture and landscapes. Overall, it was an average experience that could have been enhanced with better storytelling and a more relaxed pace." },
  { user_id: 4, route_id: 2, rating: 4, comment: "The walking tour route took us through the heart of the city, showcasing its iconic landmarks and hidden gems. The route was well-designed, allowing us to explore both popular attractions and lesser-known spots. The guide was knowledgeable and enthusiastic, sharing captivating stories about the city's history and culture. The pacing of the tour was excellent, giving us ample time to soak in the beauty of each site. The commentary provided valuable insights, deepening our appreciation for the city's rich heritage. Overall, it was a memorable experience that left us with a newfound appreciation for the city's charm and character." },
  { user_id: 5, route_id: 2, rating: 3, comment: "The walking tour route offered a decent overview of the city's attractions, but it lacked depth in its exploration. While the guide provided basic information about each landmark, there was a lack of engaging storytelling to bring the history to life. The pacing of the tour felt rushed, leaving little time for reflection at each stop. Additionally, some of the sites included in the route were underwhelming and could have been replaced with more interesting alternatives. Overall, it was an average experience that fell short of expectations in terms of depth and engagement." },
  { user_id: 6, route_id: 2, rating: 5, comment: "Embarking on the walking tour route was the highlight of our visit to the city. The route was thoughtfully planned, leading us through a captivating journey of discovery. The guide's passion for the city's history was contagious, making the tour both educational and entertaining. Each stop on the route offered something unique, from stunning architecture to hidden historical gems. The pacing of the tour was perfect, allowing us to savor every moment and capture memorable experiences. The commentary provided valuable insights, enriching our understanding of the city's cultural heritage. Overall, it was an exceptional experience that surpassed our expectations." },
  { user_id: 7, route_id: 3, rating: 4, comment: "The walking tour route provided an insightful exploration of the city's iconic landmarks. The route was well-structured, allowing us to cover a diverse range of attractions. The guide was knowledgeable and engaging, offering fascinating stories about each site we visited. The pacing of the tour was well-managed, with plenty of time to appreciate the beauty of our surroundings. The commentary provided valuable context, enhancing our appreciation for the city's history and culture. Overall, it was a memorable experience that left us with a deeper understanding of the city's heritage." },
  { user_id: 8, route_id: 3, rating: 3, comment: "The walking tour route offered a decent overview of the city's main attractions. While the route was well-organized, the guide's commentary lacked depth and enthusiasm. More engaging storytelling would have made the tour more captivating. Additionally, the pacing of the tour felt rushed at times, leaving little opportunity to fully immerse ourselves in each site. However, the route itself was scenic, providing picturesque views of the city's landmarks. Overall, it was an average experience that could have been enhanced with better narration and a more relaxed pace." },
  { user_id: 9, route_id: 3, rating: 5, comment: "Exploring the city's famous landmarks through the walking tour route was an unforgettable experience. The route was meticulously planned, taking us on a journey through the city's rich history and culture. The guide was passionate and knowledgeable, sharing captivating stories at each stop. The pacing of the tour was perfect, allowing us to appreciate the beauty of each site without feeling rushed. The commentary provided valuable insights, deepening our understanding of the city's heritage. Overall, it was an exceptional tour that exceeded our expectations in every way." },
  { user_id: 10, route_id: 4, rating: 3, comment: "The walking tour route offered a decent introduction to the city's attractions. While the route covered the major landmarks, the guide's commentary lacked depth and enthusiasm. More engaging storytelling would have made the tour more memorable. Additionally, the pacing of the tour felt rushed at times, leaving little time to fully absorb the significance of each site. However, the route itself was scenic, providing picturesque views of the city's architecture and landscapes. Overall, it was an average experience that could have been improved with better narration and a more relaxed pace." },
  { user_id: 1, route_id: 5, rating: 4, comment: "The walking tour route offered a comprehensive exploration of the city's cultural and historical landmarks. The route was well-designed, taking us through vibrant neighborhoods and iconic sites. The guide was knowledgeable and passionate, offering fascinating insights into the city's history and architecture. The pacing of the tour was perfect, allowing us to immerse ourselves in each location. The commentary provided valuable context, deepening our understanding of the city's heritage. Overall, it was an enriching experience that left us with a deeper appreciation for the city's culture." },
  { user_id: 2, route_id: 5, rating: 5, comment: "Embarking on the walking tour route was an unforgettable experience. The route was thoughtfully curated, showcasing the city's hidden gems and must-see attractions. The guide was engaging and informative, sharing captivating stories about each site we visited. The pacing of the tour was excellent, allowing us to explore each location at our own pace. The commentary provided valuable insights, enriching our understanding of the city's culture and history. Overall, it was a memorable tour that exceeded our expectations." },
  { user_id: 3, route_id: 5, rating: 3, comment: "The walking tour route provided a decent overview of the city's main attractions. While the route covered the major landmarks, some of the sites felt rushed, and we didn't have enough time to fully appreciate them. The guide's commentary was informative but lacked enthusiasm, making the tour less engaging. However, the route itself was scenic, offering picturesque views of the city's skyline and architecture. Overall, it was an average experience that could have been improved with better pacing and storytelling." },
  { user_id: 4, route_id: 6, rating: 4, comment: "Exploring the city's landmarks through the walking tour route was a delightful experience. The route was well-planned, taking us to both popular attractions and off-the-beaten-path gems. The guide was knowledgeable and engaging, providing fascinating insights into the city's history and culture. The pacing of the tour was perfect, allowing us to fully immerse ourselves in each location. The commentary provided valuable context, deepening our appreciation for the city's heritage. Overall, it was an excellent tour that left us with lasting memories." },
  { user_id: 5, route_id: 6, rating: 3, comment: "The walking tour route offered a decent overview of the city's attractions. While the route covered the major landmarks, some of the stops felt rushed, and we didn't have enough time to explore them fully. The guide's commentary was informative but lacked enthusiasm, making the tour less engaging. However, the route itself was scenic, providing picturesque views of the city's architecture and landscapes. Overall, it was an average experience that could have been improved with better pacing and storytelling." },
  { user_id: 6, route_id: 6, rating: 5, comment: "Embarking on the walking tour route was the highlight of our trip to the city. The route was well-designed, taking us on a journey through the city's history and culture. The guide was passionate and knowledgeable, providing captivating commentary at each stop. The pacing of the tour was perfect, allowing us to explore each location thoroughly. The commentary provided valuable insights, deepening our understanding of the city's heritage. Overall, it was an exceptional experience that we highly recommend to others." },
  { user_id: 7, route_id: 7, rating: 4, comment: "The walking tour route provided an insightful exploration of the city's landmarks. The route was well-organized, taking us to a diverse range of attractions. The guide was knowledgeable and engaging, offering fascinating stories about each site we visited. The pacing of the tour was well-managed, allowing us to fully appreciate the beauty of our surroundings. The commentary provided valuable context, enhancing our understanding of the city's history and culture. Overall, it was a memorable experience that left us with a deeper appreciation for the city." },
  { user_id: 8, route_id: 7, rating: 3, comment: "The walking tour route offered a decent overview of the city's main attractions. While the route covered the major landmarks, some of the stops felt rushed, and we didn't have enough time to explore them fully. The guide's commentary was informative but lacked enthusiasm, making the tour less engaging. However, the route itself was scenic, providing picturesque views of the city's skyline and architecture. Overall, it was an average experience that could have been improved with better pacing and storytelling." },
  { user_id: 9, route_id: 7, rating: 5, comment: "Exploring the city's famous landmarks through the walking tour route was an unforgettable experience. The route was meticulously planned, taking us on a journey through the city's rich history and culture. The guide was passionate and knowledgeable, sharing captivating stories at each stop. The pacing of the tour was perfect, allowing us to appreciate the beauty of each site without feeling rushed. The commentary provided valuable insights, deepening our understanding of the city's heritage. Overall, it was an exceptional tour that exceeded our expectations in every way." },
  { user_id: 10, route_id: 8, rating: 3, comment: "The walking tour route offered a decent introduction to the city's attractions. While the route covered the major landmarks, some of the stops felt rushed, and we didn't have enough time to fully appreciate them. The guide's commentary was informative but lacked enthusiasm, making the tour less engaging. However, the route itself was scenic, providing picturesque views of the city's architecture and landscapes. Overall, it was an average experience that could have been improved with better pacing and storytelling." },
  { user_id: 1, route_id: 9, rating: 4, comment: "The walking tour route provided an insightful exploration of the city's cultural and historical landmarks. The route was well-structured, taking us through vibrant neighborhoods and iconic sites. The guide was knowledgeable and enthusiastic, offering fascinating insights into the city's history and architecture. The pacing of the tour was perfect, allowing us to immerse ourselves in each location. The commentary provided valuable context, deepening our understanding of the city's heritage. Overall, it was an enriching experience that left us with a deeper appreciation for the city's culture." },
  { user_id: 2, route_id: 9, rating: 5, comment: "Embarking on the walking tour route was an unforgettable experience. The route was thoughtfully curated, showcasing the city's hidden gems and must-see attractions. The guide was engaging and informative, sharing captivating stories about each site we visited. The pacing of the tour was excellent, allowing us to explore each location at our own pace. The commentary provided valuable insights, enriching our understanding of the city's culture and history. Overall, it was a memorable tour that exceeded our expectations." },
  { user_id: 3, route_id: 9, rating: 3, comment: "The walking tour route provided a decent overview of the city's main attractions. While the route covered the major landmarks, some of the sites felt rushed, and we didn't have enough time to fully appreciate them. The guide's commentary was informative but lacked enthusiasm, making the tour less engaging. However, the route itself was scenic, offering picturesque views of the city's skyline and architecture. Overall, it was an average experience that could have been improved with better pacing and storytelling." },
  { user_id: 4, route_id: 10, rating: 4, comment: "Exploring the city's landmarks through the walking tour route was a delightful experience. The route was well-planned, taking us to both popular attractions and off-the-beaten-path gems. The guide was knowledgeable and engaging, providing fascinating insights into the city's history and culture. The pacing of the tour was perfect, allowing us to fully immerse ourselves in each location. The commentary provided valuable context, deepening our appreciation for the city's heritage. Overall, it was an excellent tour that left us with lasting memories." },
  { user_id: 5, route_id: 10, rating: 3, comment: "The walking tour route offered a decent overview of the city's attractions. While the route covered the major landmarks, some of the stops felt rushed, and we didn't have enough time to explore them fully. The guide's commentary was informative but lacked enthusiasm, making the tour less engaging. However, the route itself was scenic, providing picturesque views of the city's architecture and landscapes. Overall, it was an average experience that could have been improved with better pacing and storytelling." },
  { user_id: 6, route_id: 10, rating: 5, comment: "Embarking on the walking tour route was the highlight of our trip to the city. The route was well-designed, taking us on a journey through the city's history and culture. The guide was passionate and knowledgeable, providing captivating commentary at each stop. The pacing of the tour was perfect, allowing us to explore each location thoroughly. The commentary provided valuable insights, deepening our understanding of the city's heritage. Overall, it was an exceptional experience that we highly recommend to others." },
  { user_id: 7, route_id: 11, rating: 4, comment: "The walking tour route provided an insightful exploration of the city's landmarks. The route was well-organized, taking us to a diverse range of attractions. The guide was knowledgeable and engaging, offering fascinating stories about each site we visited. The pacing of the tour was well-managed, allowing us to fully appreciate the beauty of our surroundings. The commentary provided valuable context, enhancing our understanding of the city's history and culture. Overall, it was a memorable experience that left us with a deeper appreciation for the city." }
];

const routes = [
  {
    user_id: 1,
    route_name: 'Historic Downtown Tour',
    description: 'Explore the rich history of our city with this historic downtown tour. Visit landmarks such as the Old Town Hall, Main Street Square, and the iconic Central Library. Learn about the city’s founding and its cultural heritage.',
    is_public: true,
    origin_id: 1,
    destination_id: 2
  },
  {
    user_id: 2,
    route_name: 'Art District Exploration',
    description: 'Immerse yourself in the vibrant art scene of our city with this art district exploration. Discover hidden galleries, colorful street murals, and dynamic art installations. Meet local artists and experience the creativity of our community.',
    is_public: true,
    origin_id: 3,
    destination_id: 4
  },
  {
    user_id: 3,
    route_name: 'Culinary Delights Tour',
    description: 'Indulge your taste buds on this culinary delights tour. Sample diverse flavors from around the world as you visit local eateries, food markets, and gourmet restaurants. From street food to fine dining, experience the gastronomic wonders of our city.',
    is_public: false,
    origin_id: 5,
    destination_id: 6
  },
  {
    user_id: 1,
    route_name: 'Nature Escapade',
    description: 'Escape the hustle and bustle of the city with this nature escapade. Trek through lush forests, scenic trails, and tranquil parks. Discover hidden waterfalls, breathtaking viewpoints, and abundant wildlife. Reconnect with nature and rejuvenate your soul.',
    is_public: true,
    origin_id: 7,
    destination_id: 8
  },
  {
    user_id: 2,
    route_name: 'Family Fun Adventure',
    description: 'Embark on a family fun adventure and create lasting memories together. Visit theme parks, interactive museums, and exciting attractions. Enjoy thrilling rides, hands-on exhibits, and entertaining shows. There’s something for everyone in the family!',
    is_public: true,
    origin_id: 9,
    destination_id: 10
  },
  {
    user_id: 3,
    route_name: 'Nightlife Experience',
    description: 'Experience the vibrant nightlife of our city with this exciting tour. Explore trendy bars, cozy pubs, and lively nightclubs. Dance the night away to live music, DJs, and karaoke. Discover hidden gems and make unforgettable memories with friends.',
    is_public: false,
    origin_id: 11,
    destination_id: 12
  },
  {
    user_id: 1,
    route_name: 'Scenic Drive',
    description: 'Take a scenic drive and soak in breathtaking views of our city’s landscapes. Wind through picturesque countryside, coastal highways, and mountain roads. Stop at scenic overlooks, charming towns, and historic landmarks along the way.',
    is_public: true,
    origin_id: 13,
    destination_id: 14
  },
  {
    user_id: 2,
    route_name: 'Architectural Marvels Tour',
    description: 'Marvel at the architectural wonders of our city on this guided tour. Admire iconic skyscrapers, historic buildings, and modern landmarks. Learn about renowned architects and the stories behind each architectural masterpiece.',
    is_public: true,
    origin_id: 15,
    destination_id: 16
  },
  {
    user_id: 3,
    route_name: 'Shopping Spree',
    description: 'Indulge in a shopping spree and discover the best shopping destinations in our city. Browse chic boutiques, designer stores, and bustling markets. Find unique treasures, fashion trends, and one-of-a-kind souvenirs to take home.',
    is_public: false,
    origin_id: 17,
    destination_id: 18
  },
  {
    user_id: 1,
    route_name: 'Off-the-Beaten-Path Adventure',
    description: 'Embark on an off-the-beaten-path adventure and uncover hidden gems off the tourist trail. Explore quirky neighborhoods, local markets, and secret spots known only to locals. Experience the authentic culture, flavors, and traditions of our city.',
    is_public: true,
    origin_id: 19,
    destination_id: 20
  },
  {
    user_id: 4,
    route_name: "Historical Downtown Walk", 
    description: "Explore the rich history of our city with this guided walking tour through the heart of downtown. Discover iconic landmarks, ancient monuments, and hidden gems as you stroll through historic streets lined with architectural marvels. Learn about the city's founding fathers, pivotal moments in its history, and the stories behind its most famous buildings. Immerse yourself in the sights, sounds, and flavors of our vibrant city as you uncover its fascinating past on this memorable journey through time.",
    is_public: true,
    origin_id: 24,
    destination_id: 25
  },
  {
    user_id: 5,
    route_name: "Cultural District Discovery", 
    description: "Embark on a cultural adventure through the city's vibrant arts district. Delve into the world of art, music, and theater as you visit galleries, performance venues, and public art installations. Learn about the city's thriving creative scene, meet local artists, and experience the diversity of cultural expression that defines our community. From contemporary masterpieces to traditional crafts, this tour offers a unique perspective on the city's cultural heritage and its impact on the world stage.",
    is_public: true,
    origin_id: 26,
    destination_id: 27
  },
  {
    user_id: 6,
    route_name: "Scenic Riverfront Ramble", 
    description: "Escape the hustle and bustle of the city with a leisurely stroll along the picturesque riverfront. Discover tranquil parks, scenic overlooks, and charming waterfront cafes as you meander along the riverbanks. Learn about the city's maritime history, ecological conservation efforts, and the role of the river in shaping its identity. With breathtaking views at every turn, this scenic walk offers a refreshing retreat from urban life and a chance to reconnect with nature in the heart of the city.",
    is_public: false,
    origin_id: 28,
    destination_id: 29
  },
  {
    user_id: 4,
    route_name: "Architectural Marvels Tour", 
    description: "Uncover the city's architectural treasures on this guided tour of its most iconic buildings and landmarks. From towering skyscrapers to historic cathedrals, explore the diverse range of architectural styles that define our cityscape. Learn about the visionary architects, innovative designs, and cultural influences behind each structure as you admire their beauty and craftsmanship up close. Whether you're a design enthusiast or simply curious about the built environment, this tour promises to inspire and delight with its stunning showcase of architectural excellence.",
    is_public: true,
    origin_id: 30,
    destination_id: 31
  },
  {
    user_id: 5,
    route_name: "Culinary Delights Expedition", 
    description: "Savor the flavors of the city on this delicious culinary journey through its vibrant food scene. From street food stalls to Michelin-starred restaurants, discover the diverse culinary traditions that make our city a gastronomic paradise. Sample local specialties, exotic flavors, and international cuisines as you eat your way through bustling markets, hidden alleyways, and trendy eateries. Learn about the city's culinary heritage, meet passionate chefs, and indulge in mouthwatering dishes that will tantalize your taste buds and leave you craving more.",
    is_public: true,
    origin_id: 32,
    destination_id: 33
  },
  {
    user_id: 6,
    route_name: 'Nightlife Experience',
    description: 'Experience the vibrant nightlife of our city with this exciting tour. Explore trendy bars, cozy pubs, and lively nightclubs. Dance the night away to live music, DJs, and karaoke. Discover hidden gems and make unforgettable memories with friends.',
    is_public: false,
    origin_id: 34,
    destination_id: 35
  },
  {
    user_id: 4,
    route_name: 'Scenic Drive',
    description: 'Take a scenic drive and soak in breathtaking views of our city’s landscapes. Wind through picturesque countryside, coastal highways, and mountain roads. Stop at scenic overlooks, charming towns, and historic landmarks along the way.',
    is_public: true,
    origin_id: 36,
    destination_id: 37
  },
  {
    user_id: 5,
    route_name: "Gardens and Green Spaces Tour", 
    description: "Discover the city's lush green oases on this tranquil tour of its most beautiful gardens and parks. From botanical gardens to urban greenways, explore a variety of landscapes filled with colorful blooms, serene ponds, and shady groves. Learn about the city's horticultural heritage, sustainable gardening practices, and the importance of green spaces in urban planning. Whether you're a nature lover, a gardening enthusiast, or simply seeking a peaceful retreat from city life, this tour offers a refreshing escape into the natural beauty of our city.",
    is_public: true,
    origin_id: 38,
    destination_id: 39
  },
  {
    user_id: 6,
    route_name: 'Shopping Spree',
    description: 'Indulge in a shopping spree and discover the best shopping destinations in our city. Browse chic boutiques, designer stores, and bustling markets. Find unique treasures, fashion trends, and one-of-a-kind souvenirs to take home.',
    is_public: false,
    origin_id: 40,
    destination_id: 41
  },
  {
    user_id: 4,
    route_name: "Street Art Safari", 
    description: "Embark on an urban adventure through the city's vibrant street art scene. From colorful murals to thought-provoking installations, explore the diverse array of public art that adorns our city streets. Learn about the artists behind the artworks, their inspirations, and the messages they aim to convey. Discover hidden alleyways, bustling neighborhoods, and off-the-beaten-path galleries as you uncover the artistic soul of our city. Whether you're a seasoned art enthusiast or simply curious about the creative spirit of our community, this tour promises to inspire and delight with its vibrant showcase of urban expression.",
    is_public: true,
    origin_id: 42,
    destination_id: 43
  },
  {
    user_id: 7,
    route_name: "Historic Neighborhoods Walk", 
    description: "Step back in time and explore the city's historic neighborhoods on this fascinating walking tour. Wander through charming cobblestone streets, quaint row houses, and elegant squares as you learn about the rich history and heritage of each district. Discover hidden gems, local landmarks, and architectural gems that offer glimpses into the city's past. From bustling marketplaces to quiet residential streets, each neighborhood has its own unique story to tell, making this tour a captivating journey through the layers of our city's history.",
    is_public: true,
    origin_id: 45,
    destination_id: 46
  },
  {
    user_id: 8,
    route_name: "Urban Renewal Route", 
    description: "Witness the city's transformation on this dynamic tour of its urban renewal projects and revitalized neighborhoods. Explore formerly neglected areas that have been revitalized into thriving cultural hubs, creative spaces, and community gathering places. Learn about the visionaries, architects, and activists who have shaped the city's urban landscape and created vibrant spaces for residents and visitors alike. From adaptive reuse projects to sustainable developments, discover how the city is embracing innovation and creativity to build a more livable and inclusive urban environment.",
    is_public: true,
    origin_id: 47,
    destination_id: 48
  },
  {
    user_id: 9,
    route_name: "City at Night Tour", 
    description: "Experience the city's vibrant nightlife on this exciting tour of its illuminated landmarks and bustling entertainment districts. From neon-lit streets to lively bars and clubs, explore the city's after-dark scene with a local guide leading the way. Discover hidden gems, secret speakeasies, and rooftop lounges offering panoramic views of the city skyline. Whether you're into live music, craft cocktails, or late-night eats, this tour has something for everyone. Soak up the energy of the city after hours and discover why it truly comes alive at night.",
    is_public: false,
    origin_id: 49,
    destination_id: 50
  },
  {
    user_id: 10,
    route_name: "Harborfront Heritage Trail", 
    description: "Trace the city's maritime history along this scenic trail that winds along the harborfront. Explore historic piers, maritime museums, and working waterfronts as you learn about the city's seafaring past and present. Discover the stories of sailors, fishermen, and shipbuilders who have shaped the city's identity and economy for centuries. From scenic overlooks to bustling marinas, this trail offers breathtaking views and fascinating insights into the city's maritime heritage. Whether you're a history buff or simply enjoy waterfront walks, this tour promises a memorable journey along the shores of our city." ,
    is_public: true,
    origin_id: 51,
    destination_id: 52
  },
  {
    user_id: 7,
    route_name: "Riverside Revelations Walk", 
    description: "Follow the river's meandering path on this scenic walk that explores the city's historic waterfront and riverside parks. From tranquil nature reserves to bustling promenades, discover a variety of landscapes teeming with wildlife, flora, and fauna. Learn about the river's ecological importance, recreational opportunities, and cultural significance as you stroll along its banks. With panoramic views of the city skyline and waterfront landmarks, this walk offers a refreshing perspective on the city's natural beauty and its enduring connection to the river.",
    is_public: true,
    origin_id: 53,
    destination_id: 54
  },
  {
    user_id: 8,
    route_name: "Culinary Heritage Trail", 
    description: "Savor the flavors of the city's culinary heritage on this delicious tour of its most iconic dishes and dining establishments. From traditional recipes passed down through generations to innovative fusion cuisine, explore the diverse culinary landscape that defines our city's gastronomic identity. Meet local chefs, artisans, and food producers as you sample specialties from neighborhood markets, historic eateries, and trendy food halls. Whether you're a foodie on the hunt for authentic flavors or simply curious about the city's culinary traditions, this tour promises a mouthwatering journey through the heart of our culinary heritage." ,
    is_public: false,
    origin_id: 55,
    destination_id: 56
  },
  {
    user_id: 9,
    route_name: "Ghosts and Legends Tour", 
    description: "Uncover the city's dark and mysterious past on this spine-tingling tour of its most haunted landmarks and eerie sites. From historic cemeteries to haunted hotels, explore the shadowy corners of the city where ghostly apparitions and paranormal phenomena are said to lurk. Hear chilling tales of tragedy, betrayal, and revenge as you visit sites with a reputation for supernatural activity. Led by a knowledgeable guide, this tour offers a unique blend of history, folklore, and spine-tingling encounters that will leave you questioning what lies beyond the veil of the living." ,
    is_public: true,
    origin_id: 57,
    destination_id: 58
  },
  {
    user_id: 10,
    route_name: "Hidden Gems Expedition", 
    description: "Discover the city's best-kept secrets on this off-the-beaten-path tour of its hidden gems and lesser-known attractions. From quirky museums to eclectic street art, explore a side of the city that most visitors never see. Learn about local legends, secret histories, and the stories behind the city's most intriguing hidden treasures. With insider tips and recommendations from a knowledgeable guide, uncover hidden gems that will surprise and delight even the most seasoned travelers. Whether you're a curious explorer or a seasoned adventurer, this tour promises to reveal the city's hidden charms and unexpected surprises." ,
    is_public: true,
    origin_id: 59,
    destination_id: 60
  },
  {
    user_id: 7,
    route_name: 'Shopping Spree',
    description: 'Indulge in a shopping spree and discover the best shopping destinations in our city. Browse chic boutiques, designer stores, and bustling markets. Find unique treasures, fashion trends, and one-of-a-kind souvenirs to take home.',
    is_public: false,
    origin_id: 61,
    destination_id: 62
  },
  {
    user_id: 8,
    route_name: 'Off-the-Beaten-Path Adventure',
    description: 'Embark on an off-the-beaten-path adventure and uncover hidden gems off the tourist trail. Explore quirky neighborhoods, local markets, and secret spots known only to locals. Experience the authentic culture, flavors, and traditions of our city.',
    is_public: true,
    origin_id: 63,
    destination_id: 64
  }
]

export {
  users,
  locationRatings,
  routeRatings,
  routes
}
