const vancouverPlaces = [
  {
    place_id: 'ChIJp2zKeo1xhlQRWOMOmCcWJV8',
    city_id: 3,
    country_id: 1,
    name: 'Vancouver Aquarium',
    category: 'Aquarium',
    description: 'Popular kid-friendly attraction showcases local & exotic aquatic life with a focus on conservation.',
  },
  {
    place_id: 'ChIJo-QmrYxxhlQRFuIJtJ1jSjY',
    city_id: 3,
    country_id: 1,
    name: 'Stanley Park',
    category: 'Park',
    description: "Vancouver's largest urban park has beaches, trails & family attractions, plus a picturesque seawall.",
  },
  {
    place_id: 'ChIJG3q8d85zhlQRIH1pyAsVpEc',
    city_id: 3,
    country_id: 1,
    name: 'Granville Island Public Market',
    category: 'Market',
    description: 'Popular indoor market with restaurants, bars & cafes, plus gourmet food stalls & artisan boutiques.'
  },
  {
    place_id: 'ChIJnZHwi2NxhlQRN3CYHzc3giE',
    city_id: 3,
    country_id: 1,
    name: 'Science World',
    category: 'Museum',
    description: 'Interactive science displays & films for kids from toddlers to early teens, inside a geodesic dome.',
  },
  {
    place_id: 'ChIJwXz9f39xhlQRT3qxXAPDlbU',
    city_id: 3,
    country_id: 1,
    name: 'Vancouver Art Gallery',
    category: 'Art Gallery',
    description: 'Gallery known for its touring exhibits, work by local artists (like Emily Carr) & photo collection.',
  },
  {
    place_id: 'ChIJrf8w27NyhlQR44St4PQccfY',
    city_id: 3,
    country_id: 1,
    name: 'Museum of Anthropology at UBC',
    category: 'Museum',
    description: 'Large Arthur Erickson–designed museum at UBC devoted to cultural artifacts from around the world.',
  },
  {
    place_id: 'ChIJQ9pJmH5xhlQRe_nvreYL37k',
    city_id: 3,
    country_id: 1,
    name: 'Vancouver Public Library, Central Library',
    category: 'Library',
    description: "The city's grand central library, with a colonnaded surround reminiscent of a Roman amphitheater.",
  },
  {
    place_id: 'ChIJj1udwilyhlQR1FRRZudhLlE',
    city_id: 3,
    country_id: 1,
    name: 'Roedde House Museum',
    category: 'Museum',
    description: 'This restored, late-Victorian home with tours depicts  life at the turn of the 19th century.',
  },
  {
    place_id: 'ChIJ1eC-_HxxhlQRuxiCkf1NQPk',
    city_id: 3,
    country_id: 1,
    name: 'BC Place' ,
    category: 'Stadium',
    description: 'Stadium with a retractable roof & over 50,000 seats for events plus Major League Soccer & football.',
  },
  {
    place_id: 'ChIJSd7cANJvhlQRXg8TheyzUPM',
    city_id: 3,
    country_id: 1,
    name: 'Capilano Suspension Bridge Park',
    category: 'Historical Landmark',
    description: 'Built in 1889, this 137m-long treetop bridge offers scenic views of the forest below.',
  },
  {
    place_id: 'ChIJIcZrTvVzhlQRiKTnD03vt7Q',
    city_id: 3,
    country_id: 1,
    name: 'Queen Elizabeth Park',
    category: 'Park',
    description: 'Urban landmark on a hill featuring manicured gardens, a conservatory, sculptures & sports courts.',
  },
  {
    place_id: 'ChIJwW3HeIZzhlQRVxJgWI8VjAg',
    city_id: 3,
    country_id: 1,
    name: 'VanDusen Botanical Garden',
    category: 'Park',
    description: 'Space with ever-changing greenery, flowers & art installations plus fine dining & a casual cafe.',
  },
  {
    place_id: 'ChIJK7VbnXxxhlQRCbKQyeRwBJ4',
    city_id: 3,
    country_id: 1,
    name: 'Rogers Arena',
    category: 'Event Venue',
    description: 'Spacious venue that hosts the Vancouver Canucks & concerts by big-name touring acts.',
  },
  {
    place_id: 'ChIJ86zkaC9yhlQR4GhBA8iTiy4',
    city_id: 3,
    country_id: 1,
    name: 'English Bay Beach',
    category: 'Beach',
    description: 'Bustling beach with volleyball courts, plus a concession stand & the Cactus Club Cafe for food.',
  },
  {
    place_id: 'ChIJo4RRq4NxhlQRIAejSwZjXS0',
    city_id: 3,
    country_id: 1,
    name: 'Marine Building',
    category: 'Tourist Attraction',
    description: 'Skyscraper, opened in 1930, known for its art deco–inspired architecture & its ornate lobby.',
  },
  {
    place_id: 'ChIJ0UCTbi1yhlQRQCKD7zPvHBk',
    city_id: 3,
    country_id: 1,
    name: 'Sunset Beach',
    category: 'Beach',
    description: 'Sunset Beach in Vancouver is a picturesque waterfront destination offering stunning views of English Bay and the surrounding mountains.'
  },
  {
    place_id: 'ChIJwd1aPIBxhlQRX8pxjPkAb5s',
    city_id: 3,
    country_id: 1,
    name: 'Robson Square',
    category: 'Tourist Attraction',
    description: 'Ice-skating, street-dancing & landscape architecture in a pedestrian hub amid office towers.',
  },
  {
    place_id: 'ChIJIeDiJJ1xhlQRCWHIheB_Bbc',
    city_id: 3,
    country_id: 1,
    name: 'Canada Place',
    category: 'Convention Center',
    description: 'Built to look like a ship, this iconic complex houses a convention centre, hotel & ferry terminal.',
  },
  {
    place_id: 'ChIJK33rpNZzhlQRwA_oOKDuFDI',
    city_id: 3,
    country_id: 1,
    name: 'False Creek',
    category: 'Tourist Attraction',
    description: 'Home to 10 marinas, this inlet offers many boating activities, including pleasure boats & paddling.',
  },
  {
    place_id: 'ChIJAx7UL8xyhlQR86Iqc-fUncc',
    city_id: 3,
    country_id: 1,
    name: 'The University of British Columbia',
    category: 'University',
    description: 'Sprawling public research university known for its anthropology museum & arts & sciences programs.'
  },
  {
    place_id: 'ChIJP2oYRX9xhlQRUGL0tr-uzSY',
    city_id: 3,
    country_id: 1,
    name: 'CF Pacific Centre',
    category: 'Shopping Mall',
    description: 'Upscale mall since 1971 with premium retailers, designer brands, a food court & underground parking.'
  }
];

export default vancouverPlaces;